### ISSUE TITLE
On FTmode we can not enter qemu monitor

### ISSUE THREAD

**Issue by PJTPJT** [Cuju-ft/Cuju#13]
When start FT mode, if we use 
```
sudo nc -U /mnt/vm1.monitor
```
to enter qemu monitor
It will cause sg

Backtrace:
```
#0  _int_malloc (av=av@entry=0x7ffff6ab7b20 <main_arena>, bytes=bytes@entry=65) at malloc.c:3516
#1  0x00007ffff67762b0 in _int_realloc (av=av@entry=0x7ffff6ab7b20 <main_arena>, oldp=oldp@entry=0x1637e60, oldsize=oldsize@entry=48, nb=nb@entry=80)
    at malloc.c:4304
#2  0x00007ffff6777839 in __GI___libc_realloc (oldmem=0x1637e70, bytes=63) at malloc.c:3045
#3  0x00007ffff74507d8 in g_realloc () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#4  0x0000000000742a43 in capacity_increase (qstring=qstring@entry=0x1626320, len=len@entry=1) at qobject/qstring.c:75
#5  0x0000000000742bc5 in qstring_append_chr (qstring=0x1626320, c=112) at qobject/qstring.c:104
#6  0x000000000044c406 in monitor_puts (mon=mon@entry=0x1667580, str=0x7fff040ef28f "' for more information\n", 
    str@entry=0x7fff040ef270 "QEMU 2.8.0 monitor - type 'help' for more information\n") at /mnt/nfs/Cuju/monitor.c:339
#7  0x000000000044cfa2 in monitor_vprintf (mon=0x1667580, fmt=<optimized out>, ap=<optimized out>) at /mnt/nfs/Cuju/monitor.c:359
#8  0x000000000044d057 in monitor_vprintf (ap=0x7fffffffdd30, fmt=0x76c678 "QEMU %s monitor - type 'help' for more information\n", mon=<optimized out>)
    at /mnt/nfs/Cuju/monitor.c:354
#9  monitor_printf (mon=<optimized out>, fmt=fmt@entry=0x76c678 "QEMU %s monitor - type 'help' for more information\n") at /mnt/nfs/Cuju/monitor.c:367
#10 0x000000000044ee56 in monitor_event (opaque=0x1667580, event=<optimized out>) at /mnt/nfs/Cuju/monitor.c:3905
#11 0x00000000005311c3 in tcp_chr_new_client (chr=chr@entry=0x1617870, sioc=sioc@entry=0x7fff040ef020) at qemu-char.c:3373
#12 0x0000000000531290 in tcp_chr_accept (channel=<optimized out>, cond=<optimized out>, opaque=0x1617870) at qemu-char.c:3409
#13 0x00007ffff744b04a in g_main_context_dispatch () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#14 0x00000000006b42d5 in glib_pollfds_poll () at main-loop.c:220
#15 os_host_main_loop_wait (timeout=<optimized out>) at main-loop.c:265
#16 main_loop_wait (nonblocking=<optimized out>) at main-loop.c:513
#17 0x0000000000410fbc in main_loop () at vl.c:1984
#18 main (argc=<optimized out>, argv=<optimized out>, envp=<optimized out>) at vl.c:4725
```

**Comment by PJTPJT** [comment]
This problem not showing on latest commit
